project/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

admin.autodiscover()
urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    
    url(r'^drinks/', include('drinks.urls')),
    url(r'^recipes/', include('recipes.urls')),
    url(r'^$', TemplateView.as_view(template_name='homepage.html'), name="home"),
)

# Static URLs
urlpatterns += staticfiles_urlpatterns()

# Upload URLS
if settings.DEBUG:
    urlpatterns.insert(-2, url(r'^%s(?P<path>.*)' % settings.MEDIA_URL[1:],
        'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

project/apps/recipes/models.py
from django.db import models
from django.template.defaultfilters import slugify

from tagging.fields import TagField

class Measurement(models.Model):
    name = models.CharField(max_length=200, help_text="Name of the ingredient")

    class Meta:
        ordering = ['name',]

    def __unicode__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=200, help_text="Name of the ingredient")
    alt_name = models.CharField(max_length=200, blank=True, help_text="Alternate ingredient name")
    #preparation instructions

    class Meta:
        ordering = ['name',]

    def __unicode__(self):
        name = self.name
        if self.alt_name:
            name += " (%s)" % (self.alt_name)
        return name

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        self.alt_name = self.alt_name.lower()
        super(Item, self).save(*args, **kwargs)

class Recipe(models.Model):
    name = models.CharField(max_length=200, help_text="Name of the recipe")
    slug = models.SlugField(editable=False, unique=True)
    time = models.CharField(max_length=10, blank=True, help_text="Preparation Time")
    serves = models.PositiveIntegerField(default=1, blank=True, help_text="Number of servings")
    leftovers = models.BooleanField(default=False, help_text="Makes Leftovers")
    source = models.CharField(max_length=200, blank=True, help_text="Source, please include page number")
    source_url = models.URLField(verify_exists=True, blank=True)
    instructions = models.TextField(help_text="Instructions for Preparation")
    health = models.TextField(blank=True, help_text="Related health facts")
    equipment = models.TextField(blank=True, help_text="Equipment for Preparation")

    tags = TagField()

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return "%s" % (self.name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Recipe, self).save(*args, **kwargs)

    def get_tags(self):
        return Tag.objects.get_for_object(self)

class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe)

    order = models.PositiveIntegerField(blank=True, null=True)
    multiplier = models.PositiveIntegerField(default=1)
    amount = models.CharField(max_length=20, default="1")
    measurement = models.ForeignKey(Measurement, blank=True, null=True)
    item = models.ForeignKey(Item)
    preparation = models.CharField(max_length=200, blank=True, help_text="Short prep instruction")
    optional = models.BooleanField(default=False)

    class Meta:
        ordering = ['order','id']

    def __unicode__(self):
        name = ""
        if self.multiplier > 1:
            name += "%sx " % self.multiplier
        if self.amount != '1':
            name += "%s " % (self.amount)
        if self.amount == '1' and self.measurement:
            name += "%s " % (self.amount)
        if self.measurement:
            name += "%s " % (self.measurement)
        name += "%s %s" % (self.item, self.preparation)
        if self.optional:
            name += "*"
        return name

    def short(self):
        name = ""
        if self.multiplier > 1:
            name += "%sx " % self.multiplier
        if self.amount != '1':
            name += "%s " % (self.amount)
        if self.amount == '1' and self.measurement:
            name += "%s " % (self.amount)
        if self.measurement:
            name += "%s " % (self.measurement)
        name += "%s" % (self.preparation)
        if self.optional:
            name += "*"
        return name

project/templates/base.html
<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock title %} | Dinner</title>
        <!--link rel="stylesheet" href="{{ STATIC_URL }}css/reset.css"-->
        <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
        {% block extra_head %}
        {% endblock extra_head %}
    </head>
    <body>
        <div id="container">
            <nav>
                <ul>
                    <li><a href="{% url home %}">Welcome</a></li>
                    <li><a href="{% url recipe_list %}">Recipe List</a></li>
                    <li><a href="{% url recipe_random %}">Recipe Random</a></li>
                    <li><a href="{% url wine_list %}">Wine List</a></li>
                </ul>
            </nav>
            
            <div id="main_content">
            {% block content %}
            {% endblock content %}
            </div>

            <footer>
            {% block footer %}
            {% endblock footer %}
            </footer>
        </div>
    </body>

    <script type="text/javascript"> 
        var gaJsHost = (("https:" == document.location.protocol) ? "https://" : "http://");
        document.write(unescape("%3Cscript src='" + gaJsHost + "ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
    </script>
    {% block extra_body %}
    {% endblock extra_body %}
  
</html>

project/templates/homepage.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock title %}

{% block content %}
    <p>This is the homepage</p>
{% endblock %}

project/templates/recipe_detail.html
{% extends "base.html" %}

{% block title %}Recipe Detail{% endblock %}

{% block content %}
<h1>{{ recipe.name }}</h1>

    <p>
        Source: 
        {% if recipe.source_url %}
        <a href="{{recipe.source_url}}">{{ recipe.source }}</a>
        {% else %}
        {{ recipe.source }}
        {% endif %}
    </p>
    
    <p>Time to prepare: {{ recipe.time }}</p>
    
    <p>
    Serves: {{ recipe.serves }}
    {% if recipe.leftovers %}(Makes leftovers){% endif %}
    </p>
    
    <h2>Equipment:</h2>
    <p>
    {{ recipe.equipment|linebreaksbr }}
    </p>
    
    <h2>Ingredients:</h2>
    {% with recipe.ingredient_set.all as ingredient_list %}
    {% include "ingredient_table.html" %}
    {% endwith %}
    
    <h2>Instructions:</h2>
    <p>
    {{ recipe.instructions|safe|linebreaksbr }}
    </p>
    
    {% if recipe.health %}
    <h2>Health:</h2>
    <p>
    {{ recipe.health|linebreaksbr }}
    </p>
    {% endif %}

{% endblock %}

project/templates/recipe_list.html
{% extends "base.html" %}

{% block title %}Recipe List{% endblock %}

{% block content %}

    <ul>
    {% for recipe in recipe_list %}
    <li><a href="{% url recipe_detail recipe.slug %}">{{ recipe }}</a></li>
    {% endfor %}
    </ul>

{% endblock %}